### ISSUE TITLE
[혜지] 1주차 할 일

### ISSUE THREAD

**Issue by KangKyungRim** [TeamUStory/UStory-Frontend#2]
- [x] 이미지 캐러셀 인디케이터 추가, 클릭했을때 해당 페이지로 넘어가게 하기.
- [x] 페이지 등록시 썸네일 지정시, 등록하기 버튼 눌리지 않도록 하기.
- [x] 카카오 지도 새로고침되도록 해보기
- [x] 카카오지도 검색 기록 클릭했을때, 마커가 뜨도록 하기.
- [x] 이미지 업로드버튼 클릭 -> div 클릭하도록 하기.
- [x] 뒤로가기 버튼 어디로 보낼지 고정시키기
- [x] 검색 아이콘, 지도 아이콘 고정되는 거 수정하기.
- [x] 다이어리 선택안했을 경우, 기본이미지로 결정하기.

**Comment by hyeji17** [comment]
다이어리, 페이퍼 등록시 뒤로가기 버튼 클릭시 다이어리 리스트, 내가 기록한 페이퍼 리스트로 보내기

**Comment by hyeji17** [comment]
장소검색 페이지, 페이지네이션 추가
